export const WAIT_FOR_WINDOW_DRIVER_RESPONSE_TIMEOUT = 5000;
export const CHECK_IFRAME_EXISTENCE_INTERVAL         = 1000;
export const CHECK_IFRAME_VISIBLE_INTERVAL           = 200;
export const WAIT_IFRAME_RESPONSE_DELAY              = 500;
export const CHECK_CHILD_WINDOW_CLOSED_INTERVAL      = 200;
