exports.READ_FILE_FAILED = 'FIXTURE_CODE__READ_FILE_FAILED';
exports.JAVASCRIPT_PARSING_FAILED = 'FIXTURE_CODE__JAVASCRIPT_PARSING_FAILED';
exports.AUTH_DIRECTIVE_REDEFINITION = 'FIXTURE_CODE__AUTH_DIRECTIVE_REDEFINITION';
exports.FIXTURE_DIRECTIVE_REDEFINITION = 'FIXTURE_CODE__FIXTURE_DIRECTIVE_REDEFINITION';
exports.PAGE_DIRECTIVE_REDEFINITION = 'FIXTURE_CODE__PAGE_DIRECTIVE_REDEFINITION';
exports.INVALID_NETWORK_AUTHENTICATION_CREDENTIALS_FORMAT = 'FIXTURE_CODE__INVALID_NETWORK_AUTHENTICATION_CREDENTIALS_FORMAT';
exports.REQUIRED_FILE_ALREADY_INCLUDED = 'FIXTURE_CODE__REQUIRED_FILE_ALREADY_INCLUDED';
exports.MISPLACED_DIRECTIVE = 'FIXTURE_CODE__MISPLACED_DIRECTIVE';
exports.MISPLACED_TEST_DECLARATION = 'FIXTURE_CODE__MISPLACED_TEST_DECLARATION';
exports.DUPLICATE_TEST_NAME = 'FIXTURE_CODE__DUPLICATE_TEST_NAME';
exports.EMPTY_TEST_NAME = 'FIXTURE_CODE__EMPTY_TEST_NAME';
exports.INVALID_TEST_ASSIGNMENT = 'FIXTURE_CODE__INVALID_TEST_ASSIGNMENT';
exports.TEST_STEP_IS_NOT_A_FUNCTION_OR_MIXIN = 'FIXTURE_CODE__TEST_STEP_IS_NOT_A_FUNCTION_OR_MIXIN';
exports.ACTION_FUNC_IS_NOT_A_LAST_ENTRY = 'FIXTURE_CODE__ACTION_FUNC_IS_NOT_A_LAST_ENTRY';
exports.TEST_STEP_IS_EMPTY = 'FIXTURE_CODE__TEST_STEP_IS_EMPTY';
exports.TEST_IS_EMPTY = 'FIXTURE_CODE__TEST_IS_EMPTY';
exports.FIXTURE_DIRECTIVE_IS_UNDEFINED = 'FIXTURE_CODE__FIXTURE_DIRECTIVE_IS_UNDEFINED';
exports.PAGE_DIRECTIVE_IS_UNDEFINED = 'FIXTURE_CODE__PAGE_DIRECTIVE_IS_UNDEFINED';
exports.ASYNC_FUNC_CALL = 'FIXTURE_CODE__ASYNC_FUNC_CALL';
exports.ACTION_FUNC_CALL_IN_SHARED_CODE = 'FIXTURE_CODE__ACTION_FUNC_CALL_IN_SHARED_CODE';
exports.FAILED_LOAD_REQUIRE = 'FIXTURE_CODE__FAILED_LOAD_REQUIRE';
exports.MODULE_NOT_FOUND = 'FIXTURE_CODE__MODULE_NOT_FOUND';
exports.WRITE_FILE_FAILED = 'FIXTURE_CODE__WRITE_FILE_FAILED';
exports.INVALID_FILE_FORMAT = 'FIXTURE_CODE__INVALID_FILE_FORMAT';
exports.ELEMENT_SELECTOR_PARSING_FAILED = 'FIXTURE_CODE__ELEMENT_SELECTOR_PARSING_FAILED';
exports.ASSERTION_ARGUMENT_PARSING_FAILED = 'FIXTURE_CODE__ASSERTION_ARGUMENT_PARSING_FAILED';
exports.TEST_IS_NOT_FOUND = 'FIXTURE_CODE__TEST_IS_NOT_FOUND';
exports.TEST_NAME_CHANGED_TO_ALREADY_USED = 'FIXTURE_CODE__TEST_NAME_CHANGED_TO_ALREADY_USED';
exports.INIFRAME_FUNCTION_SHOULD_ACCEPT_TWO_ARGS = 'FIXTURE_CODE__INIFRAME_FUNCTION_SHOULD_ACCEPT_TWO_ARGS';

exports.MISPLACED_MIXIN_DECLARATION = 'FIXTURE_CODE__MISPLACED_MIXIN_DECLARATION';
exports.EMPTY_MIXIN_NAME = 'FIXTURE_CODE__EMPTY_MIXIN_NAME';
exports.DUPLICATE_MIXIN_NAME = 'FIXTURE_CODE__DUPLICATE_MIXIN_NAME';
exports.DUPLICATE_MIXIN_NAME_IN_REQUIRE = 'FIXTURE_CODE__DUPLICATE_MIXIN_NAME_IN_REQUIRE';
exports.MIXIN_IS_EMPTY = 'FIXTURE_CODE__MIXIN_IS_EMPTY';
exports.MIXIN_STEP_IS_NOT_A_FUNCTION = 'FIXTURE_CODE__MIXIN_STEP_IS_NOT_A_FUNCTION';
exports.MIXIN_STEP_IS_EMPTY = 'FIXTURE_CODE__MIXIN_STEP_IS_EMPTY';
exports.INVALID_MIXIN_ASSIGNMENT = 'FIXTURE_CODE__INVALID_MIXIN_ASSIGNMENT';
exports.MIXIN_USED_IN_MIXIN = 'FIXTURE_CODE__MIXIN_USED_IN_MIXIN';
exports.UNDEFINED_MIXIN_USED = 'FIXTURE_CODE__UNDEFINED_MIXIN_USED';

exports.FAILED_TO_READ_EXTERNAL_TEST_CASES = 'FIXTURE_CODE__FAILED_TO_READ_EXTERNAL_TEST_CASES';
exports.TEST_CASES_LIST_IS_NOT_ARRAY = 'FIXTURE_CODE__TEST_CASES_LIST_IS_NOT_ARRAY';
exports.TEST_CASES_LIST_IS_EMPTY = 'FIXTURE_CODE__TEST_CASES_LIST_IS_EMPTY';
exports.TEST_CASE_IS_NOT_AN_OBJECT = 'FIXTURE_CODE__TEST_CASE_IS_NOT_AN_OBJECT';
exports.TEST_CASE_DOESNT_CONTAIN_ANY_FIELDS = 'FIXTURE_CODE__TEST_CASE_DOESNT_CONTAIN_ANY_FIELDS';
exports.TEST_CASE_NAME_IS_NOT_A_STRING = 'FIXTURE_CODE__TEST_CASE_NAME_IS_NOT_A_STRING';
exports.DUPLICATE_TEST_CASE_NAME = 'FIXTURE_CODE__DUPLICATE_TEST_CASE_NAME';








