export default {
    ctrlA:      'ctrl+a',
    backspace:  'backspace',
    delete:     'delete',
    left:       'left',
    right:      'right',
    up:         'up',
    down:       'down',
    shiftLeft:  'shift+left',
    shiftRight: 'shift+right',
    shiftUp:    'shift+up',
    shiftDown:  'shift+down',
    shiftHome:  'shift+home',
    shiftEnd:   'shift+end',
    home:       'home',
    end:        'end',
    enter:      'enter',
    tab:        'tab',
    shiftTab:   'shift+tab',
    esc:        'esc'
};
