# Number of days of inactivity before an issue becomes stale
daysUntilStale: 600
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 10
# Issues with these labels will never be considered stale
exemptLabels:
  - "AREA: docs"
  - "FREQUENCY: critical"
  - "FREQUENCY: level 2"
  - "HELP WANTED"
  - "!IMPORTANT!"
  - "STATE: Need clarification"
  - "STATE: Need response"
  - "STATE: won't fix"
  - "support center"
  - "TYPE: bug"
# Label to use when marking an issue as stale
staleLabel: "STATE: Stale"
issues:
  # Comment to post when marking an issue as stale. Set to `false` to disable
  markComment: >
    This issue has been automatically marked as stale because it has not had any activity for a long period. It will be closed and archived if no further activity occurs. However, we may return to this issue in the future. If it still affects you or you have any additional information regarding it, please leave a comment and we will keep it open.
  # Comment to post when closing a stale issue. Set to `false` to disable
  closeComment: >
    We're closing this issue after a prolonged period of inactivity. If it still affects you, please create a new issue with up-to-date information. Thank you.
pulls:
  # Comment to post when marking an issue as stale. Set to `false` to disable
  markComment: >
    This pull request has been automatically marked as stale because it has not had any activity for a long period. It will be closed and archived if no further activity occurs. However, we may return to this pull request in the future. If it is still relevant or you have any additional information regarding it, please leave a comment and we will keep it open.
  # Comment to post when closing a stale issue. Set to `false` to disable
  closeComment: >
    We're closing this pull request after a prolonged period of inactivity. If it is still relevant, please ask for this pull request to be reopened. Thank you.
