image: cimg/node:current-browsers
pipelines:
  pull-requests:
    '**':
      - step:
          script:
            - wget -O ~/FirefoxSetup.tar.bz2 "https://download.mozilla.org/?product=firefox-latest-ssl&os=linux64"
            - sudo tar xjf ~/FirefoxSetup.tar.bz2 -C /opt
            - sudo ln -s /opt/firefox/firefox /usr/bin/firefox
            - npm ci
            - npm test

  branches:
    master:
      - step:
          script:
            - wget -O ~/FirefoxSetup.tar.bz2 "https://download.mozilla.org/?product=firefox-latest-ssl&os=linux64"
            - sudo tar xjf ~/FirefoxSetup.tar.bz2 -C /opt
            - sudo ln -s /opt/firefox/firefox /usr/bin/firefox
            - npm ci
            - npm test
