export var UNCAUGHT_JS_ERROR                               = 'CLIENT_UNCAUGHT_JS_ERROR';
export var UNCAUGHT_JS_ERROR_IN_TEST_CODE_STEP             = 'CLIENT_UNCAUGHT_JS_ERROR_IN_TEST_CODE_STEP';
export var STORE_DOM_NODE_OR_JQUERY_OBJECT                 = 'CLIENT_STORE_DOM_NODE_OR_JQUERY_OBJECT';
export var TEST_INACTIVITY                                 = 'CLIENT_TEST_INACTIVITY';
export var API_EMPTY_FIRST_ARGUMENT                        = 'CLIENT_API_EMPTY_FIRST_ARGUMENT';
export var API_INVISIBLE_ACTION_ELEMENT                    = 'CLIENT_API_INVISIBLE_ACTION_ELEMENT';
export var API_INCORRECT_DRAGGING_SECOND_ARGUMENT          = 'CLIENT_API_INCORRECT_DRAGGING_SECOND_ARGUMENT';
export var API_OK_ASSERTION_FAILED                         = 'CLIENT_API_OK_ASSERTION_FAILED';
export var API_EQUAL_ASSERTION_FAILED                      = 'CLIENT_API_EQUAL_ASSERTION_FAILED';
export var API_NOT_OK_ASSERTION_FAILED                     = "CLIENT_API_NOT_OK_ASSERTION_FAILED";
export var API_NOT_EQUAL_ASSERTION_FAILED                  = "CLIENT_API_NOT_EQUAL_ASSERTION_FAILED";
export var API_INCORRECT_PRESS_ACTION_ARGUMENT             = "CLIENT_API_INCORRECT_PRESS_ACTION_ARGUMENT";
export var API_EMPTY_TYPE_ACTION_ARGUMENT                  = "CLIENT_API_EMPTY_TYPE_ACTION_ARGUMENT";
export var API_UNEXPECTED_DIALOG                           = "CLIENT_API_UNEXPECTED_DIALOG";
export var API_EXPECTED_DIALOG_DOESNT_APPEAR               = "CLIENT_API_EXPECTED_DIALOG_DOESNT_APPEAR";
export var API_INCORRECT_SELECT_ACTION_ARGUMENTS           = 'CLIENT_API_INCORRECT_SELECT_ACTION_ARGUMENTS';
export var API_INCORRECT_WAIT_ACTION_MILLISECONDS_ARGUMENT = 'CLIENT_API_INCORRECT_WAIT_ACTION_FIRST_ARGUMENT';
export var API_INCORRECT_WAIT_FOR_ACTION_EVENT_ARGUMENT    = 'CLIENT_API_INCORRECT_WAIT_FOR_ACTION_EVENT_ARGUMENT';
export var API_INCORRECT_WAIT_FOR_ACTION_TIMEOUT_ARGUMENT  = 'CLIENT_API_INCORRECT_WAIT_FOR_ACTION_TIMEOUT_ARGUMENT';
export var API_WAIT_FOR_ACTION_TIMEOUT_EXCEEDED            = 'CLIENT_API_WAIT_FOR_ACTION_TIMEOUT_EXCEEDED';
export var API_EMPTY_IFRAME_ARGUMENT                       = 'CLIENT_API_EMPTY_IFRAME_ARGUMENT';
export var API_IFRAME_ARGUMENT_IS_NOT_IFRAME               = 'CLIENT_API_IFRAME_ARGUMENT_IS_NOT_IFRAME';
export var API_MULTIPLE_IFRAME_ARGUMENT                    = 'CLIENT_API_MULTIPLE_IFRAME_ARGUMENT';
export var API_INCORRECT_IFRAME_ARGUMENT                   = 'CLIENT_API_INCORRECT_IFRAME_ARGUMENT';
export var API_UPLOAD_CAN_NOT_FIND_FILE_TO_UPLOAD          = 'CLIENT_API_UPLOAD_CAN_NOT_FIND_FILE_TO_UPLOAD';
export var API_UPLOAD_ELEMENT_IS_NOT_FILE_INPUT            = 'CLIENT_API_UPLOAD_ELEMENT_IS_NOT_FILE_INPUT';
export var API_UPLOAD_INVALID_FILE_PATH_ARGUMENT           = 'CLIENT_API_UPLOAD_INVALID_FILE_PATH_ARGUMENT';
export var IFRAME_LOADING_TIMEOUT                          = 'CLIENT_IFRAME_LOADING_TIMEOUT';
export var IN_IFRAME_TARGET_LOADING_TIMEOUT                = 'CLIENT_IN_IFRAME_TARGET_LOADING_TIMEOUT';
export var XHR_REQUEST_TIMEOUT                             = 'CLIENT_XHR_REQUEST_TIMEOUT';

export function hasErrorStepName (err) {
    return err.code !== UNCAUGHT_JS_ERROR && err.code !== XHR_REQUEST_TIMEOUT &&
           err.code !== IFRAME_LOADING_TIMEOUT && err.code !== TEST_INACTIVITY;
}
