name: Bug Report
description: Submit the behavior you consider invalid
labels: ["TYPE: bug"]
body:
  - type: markdown
    attributes:
      value: |
        Fill the template. Share as much information about the bug as you can. Create a minimal working example that allows the TestCafe team to reliably reproduce the bug.

        Use the latest [TestCafe](https://github.com/DevExpress/testcafe/releases) version - it includes more bug fixes.

        If your tests run in Chromium-based browsers, turn [native automation](https://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode) on and off, to confirm that it doesn't affect the issue.

        Before you submit an issue, please check [our GitHub repository](https://github.com/DevExpress/testcafe/issues) for similar tickets. This may save your time (and ours).
  
  - type: textarea
    id: scenario
    attributes:
      label: What is your Scenario?
      description: >
        Describe what you'd like to do.
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: What is the Current behavior?
      description: >
        Describe the behavior you see and consider invalid.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What is the Expected behavior?
      description: >
        Describe what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: url
    attributes:
      label: What is the public URL of the test page? (attach your complete example)
      description: |
        The TestCafe team needs to be able to reproduce the bug you encountered. Include a **public** test page URL in your example. Do not share any private data, such as the secret address of your staging server, or your access credentials. Refer to this article to learn how to create an example: [How To: Create a Minimal Working Example When You Submit an Issue](https://testcafe.io/402636/faq#how-to-create-a-minimal-working-example-when-you-submit-an-issue).
    validations:
      required: true

  - type: textarea
    id: testcase
    attributes:
      label: What is your TestCafe test code?
      description: >
        Paste your complete test code including all the referenced modules, if any.
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Your complete configuration file
      description: >
        Paste your complete configuration file (e.g., .testcaferc.js or .testcaferc.json).
    validations:
      required: false

  - type: textarea
    id: report
    attributes:
      label: Your complete test report
      description: >
        Paste the complete test report here (even if it is huge).
    validations:
      required: false

  - type: textarea
    id: screenhots
    attributes:
      label: Screenshots
      description: >
        If applicable, attach screenshots to help explain the issue.
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: >
        Describe what we should do to reproduce the behavior you encountered.
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: markdown
    id: environment
    attributes:
      value: >
        Your Environment details:

  - type: input
    id: version
    attributes:
      label: TestCafe version
      description: >
        Run `testcafe -v`
    validations:
      required: true

  - type: input
    id: nodejs
    attributes:
      label: Node.js version
      description: >
        Run `node -v`
    validations:
      required: false

  - type: input
    id: cmdline
    attributes:
      label: Command-line arguments
      description: >
        Example: testcafe edge,chrome -e test.js
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser name(s) and version(s)
      description: >
        Example: Edge 116, Chrome 116, Firefox 117, etc.
    validations:
      required: false

  - type: input
    id: platform
    attributes:
      label: Platform(s) and version(s)
      description: >
        Example: macOS 10.14, Windows, Linux Ubuntu 18.04.1, iOS 13
    validations:
      required: false

  - type: textarea
    id: other
    attributes:
      label: Other
      description: >
        Any notes you consider important
    validations:
      required: false
