name: Question
description: Route your questions to StackOverflow
labels: ["TYPE: question"]

body:
  - type: markdown
    attributes:
      value: |
        For TestCafe API, usage and configuration inquiries, we recommend [StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions.

        We try to keep the GitHub issues tracker for bugs and feature requests only (see also: [Contributing](https://github.com/DevExpress/testcafe#contributing)).

        You may also find answers in our up-to-date [documentation](https://testcafe.io/documentation/402635/getting-started) and [answered questions](https://stackoverflow.com/questions/tagged/testcafe) on StackOverflow. This may save your time.

        If you have already looked there and have not found an appropriate answer, [file a new question on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe).
  
  - type: input
    id: url
    attributes:
      label: File a new question on StackOverflow
      value: |
        https://stackoverflow.com/questions/ask?tags=testcafe
    validations:
      required: false
