export const JS_CONFIGURATION_EXTENSION   = '.js';
export const JSON_CONFIGURATION_EXTENSION = '.json';
export const CONFIGURATION_EXTENSIONS     = [JS_CONFIGURATION_EXTENSION, JSON_CONFIGURATION_EXTENSION];
