export default {
    src:                         'src',
    browsers:                    'browsers',
    concurrency:                 'concurrency',
    filter:                      'filter',
    reporter:                    'reporter',
    ssl:                         'ssl',
    skipUncaughtErrors:          'skipUncaughtErrors',
    speed:                       'speed',
    screenshotPath:              'screenshotPath',
    screenshotPathPattern:       'screenshotPathPattern',
    takeScreenshotsOnFails:      'takeScreenshotsOnFails',
    proxyBypass:                 'proxyBypass',
    appCommand:                  'appCommand',
    appInitDelay:                'appInitDelay',
    disableTestSyntaxValidation: 'disableTestSyntaxValidation',
    skipJsErrors:                'skipJsErrors',
    disablePageReloads:          'disablePageReloads',
    quarantineMode:              'quarantineMode',
    debugMode:                   'debugMode',
    debugOnFail:                 'debugOnFail',
    skipUncaughtErrors:          'skipUncaughtErrors',
    stopOnFirstFail:             'stopOnFirstFail'
};
