exports.CONFIG_SAVING_FAILED = 'CONFIG_SAVING_FAILED';
//Injector
exports.INJECTOR_RESOURCE_DECODING_FAILED = 'INJECTOR_RESOURCE_DECODING_FAILED';
exports.INJECTOR_RESOURCE_CHARSET_DECODING_FAILED = 'INJECTOR_RESOURCE_CHARSET_DECODING_FAILED';
exports.INJECTOR_DOCUMENT_PARSING_FAILED = 'INJECTOR_DOCUMENT_PARSING_FAILED';
exports.INJECTOR_RESOURCE_ENCODING_FAILED = 'INJECTOR_RESOURCE_ENCODING_FAILED';

//Proxy
exports.PROXY_PORT_IS_ALREADY_IN_USE = 'PROXY_PORT_IS_ALREADY_IN_USE';
exports.PROXY_ORIGIN_SERVER_CONNECTION_TERMINATED = 'PROXY_ORIGIN_SERVER_CONNECTION_TERMINATED';
exports.PROXY_CANT_RESOLVE_ORIGIN_URL = 'PROXY_CANT_RESOLVE_ORIGIN_URL';
exports.PROXY_XHR_REQUEST_SAME_ORIGIN_POLICY_VIOLATION = 'PROXY_XHR_REQUEST_SAME_ORIGIN_POLICY_VIOLATION';
exports.PROXY_ORIGIN_SERVER_REQUEST_TIMEOUT = 'PROXY_ORIGIN_SERVER_REQUEST_TIMEOUT';