name: Test Client (Desktop)

on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'The test commit SHA or ref'
        required: true
        default: 'master'
      merged_sha:
        description: 'The merge commit SHA'
      deploy_run_id:
        description: 'The ID of a deployment workspace run with artifacts'
jobs:
  test:
    uses: ./.github/workflows/test-client.yml
    with:
      test-script: 'npx gulp test-client-travis-run --steps-as-tasks'
      browsers: '["microsoftedge", "chrome", "firefox", "safari"]'
    secrets: inherit